/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.utn.gendoc.view;

import ec.edu.utn.gendoc.model.Archivo;
import ec.edu.utn.gendoc.model.CopiarDirectorio;
import ec.edu.utn.gendoc.model.GenDocUtil;
import java.awt.Checkbox;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ComponentListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author xrea
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public static String dirpath = ".";
    List<String> extension = new ArrayList<String>();
    List<String> extenAgregada = new ArrayList<>();
    static String extencionHtml = ".html";

    public Principal() {

        initComponents();
        label1.setVisible(false);
        txtProyecto.setText("menu");
        String carpetaActual = null;
        String txtRutaPlantillaHTML1 = System.getProperty("user.dir") + "/plantillas/index3.html";
        System.out.println("Carpeta actual: " + carpetaActual);
        txtCarpetaInicial.setText(System.getProperty("user.dir"));
        txtRutaPlantillaHTML.setVisible(false);
        txtIniciodestinocopia.setVisible(false);
        btndestinoCopia.setVisible(false);
        txtdestinocopia.setVisible(false);
        panelSecundarioExtens.setVisible(false);
        txtExtensionN.setVisible(false);
        txtResultadoExtensionA.setVisible(false);
        btnExtensionNueva.setVisible(false);
        btnEliminarExten.setVisible(false);
        btnActualiEx.setVisible(false);
        btnCrearExt.setVisible(false);
        panelExtensiones.setVisible(false);
        //txtRutaPlantillaHTML.setText(System.getProperty("user.dir") + "/plantillas/index3.html");
        txtRutaArchivoResultado.setText(System.getProperty("user.dir") + "/" + txtProyecto.getText() + ".html");
        btnAbrir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRutaPlantillaHTML = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCarpetaInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProyecto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRutaArchivoResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxTipoSave = new javax.swing.JComboBox<>();
        cmdGenerar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnBuscarRuta = new javax.swing.JButton();
        btndestinoCopia = new javax.swing.JButton();
        txtdestinocopia = new javax.swing.JTextField();
        txtIniciodestinocopia = new javax.swing.JTextField();
        panelExtensiones = new javax.swing.JPanel();
        chboxOdt = new javax.swing.JCheckBox();
        chbxDocs = new javax.swing.JCheckBox();
        chbxHtml = new javax.swing.JCheckBox();
        chbxTxt = new javax.swing.JCheckBox();
        chbxPdf = new javax.swing.JCheckBox();
        chbxMd = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        btnExtensionNueva = new javax.swing.JButton();
        txtExtensionN = new javax.swing.JTextField();
        btnCrearExt = new javax.swing.JButton();
        panelSecundarioExtens = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoExtensionA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxExtension = new javax.swing.JComboBox<>();
        btnEliminarExten = new javax.swing.JButton();
        btnActualiEx = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jPanel2 = new FondoPanel3();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRutaPlantillaHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaPlantillaHTMLActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Carpeta para escanear:");

        txtCarpetaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarpetaInicialActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Proyecto:");

        txtProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProyectoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Menu HTML resultado:");

        txtRutaArchivoResultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutaArchivoResultadoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cómo desea guardar:");

        cbxTipoSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxTipoSave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solo Menú", "Copiar Contenido" }));
        cbxTipoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoSaveActionPerformed(evt);
            }
        });

        cmdGenerar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdGenerar.setText("Generar menú");
        cmdGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGenerarActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResultado.setText("Resultado:");

        btnBuscarRuta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarRuta.setText("Buscar Carpeta");
        btnBuscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutaActionPerformed(evt);
            }
        });

        btndestinoCopia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndestinoCopia.setText("Carpeta Destino");
        btndestinoCopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndestinoCopiaActionPerformed(evt);
            }
        });

        panelExtensiones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        chboxOdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chboxOdt.setText(".odt");

        chbxDocs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbxDocs.setText(".docx");
        chbxDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxDocsActionPerformed(evt);
            }
        });

        chbxHtml.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbxHtml.setText(".html");
        chbxHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxHtmlActionPerformed(evt);
            }
        });

        chbxTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbxTxt.setText(".txt");

        chbxPdf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbxPdf.setText(".pdf");

        chbxMd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbxMd.setText(".md");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Extensiónes Aceptadas");

        javax.swing.GroupLayout panelExtensionesLayout = new javax.swing.GroupLayout(panelExtensiones);
        panelExtensiones.setLayout(panelExtensionesLayout);
        panelExtensionesLayout.setHorizontalGroup(
            panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtensionesLayout.createSequentialGroup()
                .addGroup(panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExtensionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chboxOdt)
                            .addComponent(chbxDocs)
                            .addComponent(chbxHtml))
                        .addGap(18, 18, 18)
                        .addGroup(panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbxTxt)
                            .addComponent(chbxPdf)
                            .addComponent(chbxMd)))
                    .addGroup(panelExtensionesLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelExtensionesLayout.setVerticalGroup(
            panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtensionesLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addGroup(panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chboxOdt)
                    .addComponent(chbxTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbxDocs)
                    .addComponent(chbxPdf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExtensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbxHtml)
                    .addComponent(chbxMd))
                .addContainerGap())
        );

        btnExtensionNueva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExtensionNueva.setText("Añadir otra extensión");
        btnExtensionNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtensionNuevaActionPerformed(evt);
            }
        });

        txtExtensionN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExtensionNActionPerformed(evt);
            }
        });

        btnCrearExt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrearExt.setText("Añadir");
        btnCrearExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearExtActionPerformed(evt);
            }
        });

        panelSecundarioExtens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtResultadoExtensionA.setColumns(20);
        txtResultadoExtensionA.setRows(5);
        jScrollPane1.setViewportView(txtResultadoExtensionA);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Extenciónes Agregadas");

        javax.swing.GroupLayout panelSecundarioExtensLayout = new javax.swing.GroupLayout(panelSecundarioExtens);
        panelSecundarioExtens.setLayout(panelSecundarioExtensLayout);
        panelSecundarioExtensLayout.setHorizontalGroup(
            panelSecundarioExtensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundarioExtensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(panelSecundarioExtensLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSecundarioExtensLayout.setVerticalGroup(
            panelSecundarioExtensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundarioExtensLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setText("Nombre Extensión:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Seleccionar:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Seleccione Tipo Extención:");

        cbxExtension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxExtension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generar Todas", "Seleccionar extensión" }));
        cbxExtension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxExtensionActionPerformed(evt);
            }
        });

        btnEliminarExten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarExten.setText("Eliminar Extensión");
        btnEliminarExten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarExtenActionPerformed(evt);
            }
        });

        btnActualiEx.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualiEx.setText("Actualizar");
        btnActualiEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiExActionPerformed(evt);
            }
        });

        btnAbrir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAbrir.setText("Abrir Menú");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmdGenerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAbrir)
                                .addGap(194, 194, 194))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(lblResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtIniciodestinocopia, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCarpetaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(txtdestinocopia)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarRuta)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRutaArchivoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btndestinoCopia)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2)
                                        .addGap(33, 33, 33)
                                        .addComponent(cbxTipoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(panelExtensiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(label1)
                                            .addComponent(btnExtensionNueva)
                                            .addComponent(txtExtensionN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCrearExt))
                                        .addGap(119, 119, 119)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(panelSecundarioExtens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnEliminarExten)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnActualiEx))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel8)
                                        .addGap(37, 37, 37)
                                        .addComponent(cbxExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxTipoSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(cbxExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarpetaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscarRuta)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndestinoCopia)
                    .addComponent(txtdestinocopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelExtensiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExtensionNueva)
                                .addGap(9, 9, 9)
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtExtensionN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCrearExt))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarExten)
                            .addComponent(btnActualiEx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSecundarioExtens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRutaArchivoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdGenerar)
                            .addComponent(btnAbrir))
                        .addGap(18, 18, 18)
                        .addComponent(lblResultado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIniciodestinocopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel9.setText("GESTOR DE DOCUMENTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtRutaPlantillaHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 729, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaPlantillaHTML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGenerarActionPerformed

        try {
            //------------
            File directorio = new File(""); //Creas un nuevo directorio a nivel de tu jar.
            directorio.mkdirs();
            directorio.setWritable(true);
            //copias la direccion
            String archivo = directorio.getCanonicalPath() + File.pathSeparator + "index3.html";
            //nuevo archivo en esa direccion
            File temp = new File(archivo);
            InputStream is = this.getClass().getResourceAsStream("/ec/edu/utn/gendoc/view/index3.html");
            FileOutputStream archivoDestino = new FileOutputStream(temp);
            FileWriter fw = new FileWriter(temp);
            byte[] buffer = new byte[512 * 1024];
            //lees el archivo hasta que se acabe...
            int nbLectura;
            while ((nbLectura = is.read(buffer)) != -1) {
                archivoDestino.write(buffer, 0, nbLectura);
            }
            //cierras el archivo,el inputS y el FileW
            fw.close();
            archivoDestino.close();
            is.close();
            //abres el archivo temporal   
            txtRutaPlantillaHTML.setText(temp.getAbsolutePath());
            temp.deleteOnExit();
        } catch (Exception e) {
        }

        extension.clear();
        txtRutaArchivoResultado.setText(""
                + txtCarpetaInicial.getText() + "/" + txtProyecto.getText() + ".html");
        if (chboxOdt.isSelected()) {
            extension.add(".odt");
        }
        if (chbxHtml.isSelected()) {
            extension.add(".html");
        }
        if (chbxTxt.isSelected()) {
            extension.add(".txt");
        }
        if (chbxDocs.isSelected()) {
            extension.add(".docx");
        }
        if (chbxMd.isSelected()) {
            extension.add(".md");
        }
        if (chbxPdf.isSelected()) {
            extension.add(".pdf");
        }
//        if (extencionHtml.equals(".html")) {
//            extension.add(".html");
//        }
        if (extenAgregada.size() > 0) {
            for (int i = 0; i < extenAgregada.size(); i++) {
                extension.add(extenAgregada.get(i));
            }
        }

        GenDocUtil gd = new GenDocUtil();
        if (txtCarpetaInicial.getText().equals(System.getProperty("user.dir"))) {
            txtRutaArchivoResultado.setText(System.getProperty("user.dir") + "/" + txtProyecto.getText() + ".html");
            if ((cbxTipoSave.getSelectedItem().toString()).equals("Solo Menú")) {

                try {
                    gd.generarArchivoFinalHTML(txtCarpetaInicial.getText(), txtRutaPlantillaHTML.getText(),
                            txtRutaArchivoResultado.getText(), extension, cbxExtension.getSelectedItem().toString(), txtProyecto.getText());
                    Date fecha = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy hh:mm:ss");
                    lblResultado.setText("Resultado: menu HTML generado. " + sdf.format(fecha));
                    Archivo archivoRaiz = gd.escanearDirectorios(txtCarpetaInicial.getText(), extension, cbxExtension.getSelectedItem().toString());
                    gd.imprimirListadoArchivosEnConsola(archivoRaiz);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if ((cbxTipoSave.getSelectedItem().toString()).equals("Copiar Contenido")) {

                try {
                    if (txtdestinocopia.getText().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "No selecciono el destino de la copia");
                    } else {
                        txtIniciodestinocopia.setText(System.getProperty("user.dir"));
                        gd.generarArchivoFinalHTML(txtCarpetaInicial.getText(), txtRutaPlantillaHTML.getText(),
                                txtRutaArchivoResultado.getText(), extension, cbxExtension.getSelectedItem().toString(), txtProyecto.getText());
                        Date fecha = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy hh:mm:ss");
                        lblResultado.setText("Resultado: menu HTML generado. " + sdf.format(fecha));
                        Archivo archivoRaiz = gd.escanearDirectorios(txtCarpetaInicial.getText(), extension, cbxExtension.getSelectedItem().toString());
                        gd.imprimirListadoArchivosEnConsola(archivoRaiz);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("ini" + txtIniciodestinocopia.getText());
                System.out.println("fin" + txtdestinocopia.getText());
                CopiarDirectorio cop = new CopiarDirectorio();

                cop.copiarDirectorio(txtIniciodestinocopia.getText(), txtdestinocopia.getText(), extension, cbxExtension.getSelectedItem().toString(), txtProyecto.getText());

            } else {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un item Para guardat");
            }
        } else {
            if ((cbxTipoSave.getSelectedItem().toString()).equals("Solo Menú")) {

                try {
                    gd.generarArchivoFinalHTML(txtCarpetaInicial.getText(), txtRutaPlantillaHTML.getText(),
                            txtRutaArchivoResultado.getText(), extension, cbxExtension.getSelectedItem().toString(), txtProyecto.getText());
                    Date fecha = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy hh:mm:ss");
                    lblResultado.setText("Resultado: menu HTML generado. " + sdf.format(fecha));
                    Archivo archivoRaiz = gd.escanearDirectorios(txtCarpetaInicial.getText(), extension, cbxExtension.getSelectedItem().toString());
                    gd.imprimirListadoArchivosEnConsola(archivoRaiz);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if ((cbxTipoSave.getSelectedItem().toString()).equals("Copiar Contenido")) {
                try {
                    if (txtdestinocopia.getText().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "No selecciono el destino de la copia");
                    } else {
                        gd.generarArchivoFinalHTML(txtCarpetaInicial.getText(), txtRutaPlantillaHTML.getText(),
                                txtRutaArchivoResultado.getText(), extension, cbxExtension.getSelectedItem().toString(), txtProyecto.getText());
                        Date fecha = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy hh:mm:ss");
                        lblResultado.setText("Resultado: menu HTML generado. " + sdf.format(fecha));
                        Archivo archivoRaiz = gd.escanearDirectorios(txtCarpetaInicial.getText(), extension, cbxExtension.getSelectedItem().toString());
                        gd.imprimirListadoArchivosEnConsola(archivoRaiz);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("ini" + txtIniciodestinocopia.getText());
                System.out.println("fin" + txtdestinocopia.getText());
                CopiarDirectorio cop = new CopiarDirectorio();
                cop.copiarDirectorio(txtIniciodestinocopia.getText(), txtdestinocopia.getText(), extension, cbxExtension.getSelectedItem().toString(), txtProyecto.getText());
//                JOptionPane.showMessageDialog(rootPane, "Copiado exitoso");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un item");
            }
        }
        extenAgregada.clear();
        btnAbrir.setVisible(true);
    }//GEN-LAST:event_cmdGenerarActionPerformed

    private void txtRutaPlantillaHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaPlantillaHTMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaPlantillaHTMLActionPerformed

    private void txtCarpetaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarpetaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarpetaInicialActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu regresar = new Menu();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBuscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutaActionPerformed
//        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        String choosertitle = null;
        chooser.setDialogTitle(choosertitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            txtCarpetaInicial.setText("getCurrentDirectory(): "
                    + chooser.getCurrentDirectory());
            txtCarpetaInicial.setText(""
                    + chooser.getSelectedFile());
//            txtRutaArchivoResultado.setText(""
//                    + chooser.getSelectedFile() + "/" + txtProyecto.getText() + ".html");
            txtIniciodestinocopia.setText("" + chooser.getSelectedFile());
        } else {
//            txtProyecto.setText("No Selection ");
        }
//        JFileChooser jf = new JFileChooser();
//        jf.showOpenDialog(this);

//        File archivo = jf.getSelectedFile();
//        if (archivo != null) {
//            txtProyecto.setText(jf.getSelectedFile().getAbsolutePath().toString());
//        }
//     JFileChooser jfc = new JFileChooser(dirpath);
//     jfc.showOpenDialog(this);
//    dirpath =jfc.getSelectedFile().getAbsolutePath().toString();
//    
//    txtProyecto.setText(dirpath);
    }//GEN-LAST:event_btnBuscarRutaActionPerformed

    private void txtRutaArchivoResultadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutaArchivoResultadoKeyReleased
        // TODO add your handling code here:
        txtRutaArchivoResultado.setText(txtRutaArchivoResultado.getText() + "/" + txtProyecto.getText() + ".html");
    }//GEN-LAST:event_txtRutaArchivoResultadoKeyReleased

    private void btndestinoCopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndestinoCopiaActionPerformed
        // TODO add your handling code here:
        if (btndestinoCopia.isEnabled()) {
            txtdestinocopia.setVisible(true);
        }
        if (cbxExtension.getSelectedItem().toString().equals("Seleccionar extensión")) {
            panelExtensiones.setVisible(true);
            btnExtensionNueva.setVisible(true);
        } else {
            panelExtensiones.setVisible(false);
            btnExtensionNueva.setVisible(false);
        }

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        String choosertitle = null;
        chooser.setDialogTitle(choosertitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
//            txtCarpetaInicial.setText("getCurrentDirectory(): "
//                    + chooser.getCurrentDirectory());
//            txtCarpetaInicial.setText(""
//                    + chooser.getSelectedFile());
            txtdestinocopia.setText(""
                    + chooser.getSelectedFile());
        } else {
            txtProyecto.setText("No Selection ");
        }

//        if(btndestinoCopia.isEnabled()){
//            txtdestinocopia.setVisible(true);
//        }
//            
        
    }//GEN-LAST:event_btndestinoCopiaActionPerformed

    private void cbxTipoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoSaveActionPerformed
        // TODO add your handling code here:
        if (cbxTipoSave.getSelectedItem().toString().equals("Copiar Contenido")) {
            btndestinoCopia.setVisible(true);
            txtdestinocopia.setVisible(true);
        } else {
            btndestinoCopia.setVisible(false);
            panelExtensiones.setVisible(false);
            btnExtensionNueva.setVisible(false);
            txtdestinocopia.setVisible(false);
        }
    }//GEN-LAST:event_cbxTipoSaveActionPerformed

    private void chbxDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxDocsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxDocsActionPerformed

    private void btnExtensionNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtensionNuevaActionPerformed
        // TODO add your handling code here:
        label1.setVisible(true);
        if (btnExtensionNueva.isEnabled() && cbxExtension.getSelectedItem().toString().equals("Seleccionar extensión")) {
            txtExtensionN.setVisible(true);
            btnCrearExt.setVisible(true);
            panelSecundarioExtens.setVisible(true);
        } else {
            txtExtensionN.setVisible(false);
            btnCrearExt.setVisible(false);
        }
    }//GEN-LAST:event_btnExtensionNuevaActionPerformed
    public void ImprimirExtenciones() {
        String strCadena = "";
        for (int i = 0; i < extenAgregada.size(); i++) {
            strCadena += extenAgregada.get(i) + "\n";
        }
        txtResultadoExtensionA.setText(strCadena);

    }

    private void btnCrearExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearExtActionPerformed
        // TODO add your handling code here:
        try {
            if (txtExtensionN.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese una extensión ");
            } else {
                txtResultadoExtensionA.setText("");
                if (btnCrearExt.isEnabled()) {
                    panelSecundarioExtens.setVisible(true);
                    txtResultadoExtensionA.setVisible(true);
                    txtResultadoExtensionA.setEditable(false);
                    extenAgregada.add(txtExtensionN.getText());
                    btnEliminarExten.setVisible(true);
                    btnActualiEx.setVisible(true);
                }
            }
            for (String a : extenAgregada) {
                txtResultadoExtensionA.append(a + "\n");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese una extensión ");
        }

    }//GEN-LAST:event_btnCrearExtActionPerformed

    private void txtProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProyectoActionPerformed

    private void txtExtensionNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExtensionNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExtensionNActionPerformed

    private void cbxExtensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxExtensionActionPerformed
        // TODO add your handling code here:
        if (cbxExtension.getSelectedItem().toString().equals("Generar Todas")) {
            panelExtensiones.setVisible(false);
            btnExtensionNueva.setVisible(false);
            btnEliminarExten.setVisible(false);
            btnActualiEx.setVisible(false);
            panelSecundarioExtens.setVisible(false);
            label1.setVisible(false);
            txtExtensionN.setVisible(false);
            btnCrearExt.setVisible(false);
        } else if (cbxExtension.getSelectedItem().toString().equals("Seleccionar extensión")) {
            panelExtensiones.setVisible(true);
            btnExtensionNueva.setVisible(true);
        }
    }//GEN-LAST:event_cbxExtensionActionPerformed

    private void chbxHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxHtmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxHtmlActionPerformed

    private void btnEliminarExtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarExtenActionPerformed
        // TODO add your handling code here:

        try {
            txtResultadoExtensionA.setText("Extensión Eliminada: " + (extenAgregada.get(extenAgregada.size() - 1)));
            extenAgregada.remove(extenAgregada.size() - 1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "No tiene más elementos");
        }


    }//GEN-LAST:event_btnEliminarExtenActionPerformed

    private void btnActualiExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiExActionPerformed
        // TODO add your handling code here:
        ImprimirExtenciones();
    }//GEN-LAST:event_btnActualiExActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        try {
            File path = new File(txtRutaArchivoResultado.getText());
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnActualiEx;
    private javax.swing.JButton btnBuscarRuta;
    private javax.swing.JButton btnCrearExt;
    private javax.swing.JButton btnEliminarExten;
    private javax.swing.JButton btnExtensionNueva;
    private javax.swing.JButton btndestinoCopia;
    private javax.swing.JComboBox<String> cbxExtension;
    private javax.swing.JComboBox<String> cbxTipoSave;
    private javax.swing.JCheckBox chboxOdt;
    private javax.swing.JCheckBox chbxDocs;
    private javax.swing.JCheckBox chbxHtml;
    private javax.swing.JCheckBox chbxMd;
    private javax.swing.JCheckBox chbxPdf;
    private javax.swing.JCheckBox chbxTxt;
    private javax.swing.JButton cmdGenerar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel panelExtensiones;
    private javax.swing.JPanel panelSecundarioExtens;
    private javax.swing.JTextField txtCarpetaInicial;
    private javax.swing.JTextField txtExtensionN;
    private javax.swing.JTextField txtIniciodestinocopia;
    private javax.swing.JTextField txtProyecto;
    private javax.swing.JTextArea txtResultadoExtensionA;
    private javax.swing.JTextField txtRutaArchivoResultado;
    private javax.swing.JTextField txtRutaPlantillaHTML;
    private javax.swing.JTextField txtdestinocopia;
    // End of variables declaration//GEN-END:variables
class FondoPanel3 extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
//            imagen = new ImageIcon(System.getProperty("user.dir") + "/src/main/java/imagenes/logo-utn.png").getImage();
            imagen = new ImageIcon(getClass().getResource("/ec/edu/utn/gendoc/imagenes/logo_csoft.png")).getImage();
//        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            g.drawImage(imagen, 0, 0, 100, 105, this);
            setOpaque(false);
            super.paint(g);
        }
    }

    class FondoPanel2 extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
//            imagen = new ImageIcon(System.getProperty("user.dir") + "/src/main/java/imagenes/logo-utn.png").getImage();
            imagen = new ImageIcon(getClass().getResource("/ec/edu/utn/gendoc/imagenes/logo_csoft.png")).getImage();
//        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            g.drawImage(imagen, 0, 0, 200, 205, this);
            setOpaque(false);
            super.paint(g);
        }
    }

    class FondoPanel1 extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
//            imagen = new ImageIcon(System.getProperty("user.dir") + "/src/main/java/imagenes/logo-utn.png").getImage();
            imagen = new ImageIcon(getClass().getResource("/ec/edu/utn/gendoc/imagenes/logo_csoft.png")).getImage();
//        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            g.drawImage(imagen, 0, 0, 200, 205, this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
